services:
  # n8n Service
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - n8n-data:/home/node/.n8n
      - /local-files:/files
    networks:
      - chatbot

volumes:
  n8n-data:
    external: true
    name: n8n-data

networks:
  chatbot:
    driver: bridge
    external: true