global:
  checkNewVersion: true
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true 

# Enable traefik UI
api:
  dashboard: true
  insecure: true

# Define entry points
entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: :443
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: $DOMAIN
            sans:
              - '*.$DOMAIN'
      middlewares:
        - securityHeaders@file

# Enable providers
providers:
  providersThrottleDuration: 2s

  file:
    watch: true
    filename: /etc/traefik/config.yml

  docker:
    watch: true
    network: chatbot
    swarmModeRefreshSeconds: 15s
    exposedByDefault: false

# Generate SSL certificates
certificatesResolvers:
  letsencrypt:
    acme:
      email: $SSL_CERTIFICATION_EMAIL
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web