global:
  checkNewVersion: true
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true 

# Enable traefik UI
api:
  dashboard: true
  insecure: true

# Define entry points
entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: :443
    http:
      tls:
        certResolver: letsencrypt
      middlewares:
        - securityHeaders@file

# Enable providers
providers:
  providersThrottleDuration: 2s

  file:
    watch: true
    filename: /etc/traefik/config.yml

  docker:
    watch: true
    network: chatbot
    exposedByDefault: false

# Generate SSL certificates
certificatesResolvers:
  letsencrypt:
    acme:
      email: "bhavyshekhaliya245@gmail.com" # 📌
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: http