services:
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    ports:
      - 7777:3000
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - chatbot 

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    ports:
      - 7778:3000
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - chatbot   

networks:
  chatbot:
    driver: bridge
    external: true