services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis-data:/data
    networks:
      - chatbot

volumes:
  redis-data:      

networks:
  chatbot:
    driver: bridge
    external: true  